# Generated by Django 5.1.7 on 2025-03-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanicalwatch',
            old_name='brand',
            new_name='_Brand',
        ),
        migrations.RenameField(
            model_name='mechanicalwatch',
            old_name='model',
            new_name='_Model',
        ),
        migrations.RenameField(
            model_name='mechanicalwatch',
            old_name='type_of_machinery',
            new_name='_Type_of_machinery',
        ),
        migrations.RenameField(
            model_name='quartzwatch',
            old_name='brand',
            new_name='_Brand',
        ),
        migrations.RenameField(
            model_name='quartzwatch',
            old_name='model',
            new_name='_Model',
        ),
        migrations.RenameField(
            model_name='quartzwatch',
            old_name='type_of_machinery',
            new_name='_Type_of_machinery',
        ),
        migrations.RenameField(
            model_name='smartwatch',
            old_name='brand',
            new_name='_Brand',
        ),
        migrations.RenameField(
            model_name='smartwatch',
            old_name='model',
            new_name='_Model',
        ),
        migrations.RenameField(
            model_name='smartwatch',
            old_name='type_of_machinery',
            new_name='_Type_of_machinery',
        ),
    ]
